# Auto-generated by scripts/extract_simulation_pins.jl
# Source: _TSCOPF_simulations/RESULTS/bound_compare_2nd_kron_constraint
const BOUND_COMPARE_2ND_KRON_SUITE = "bound_compare_2nd_kron"

const BOUND_COMPARE_2ND_KRON_PINS = (
    obj_eur = 10945.875606693349,
    pg_mw = (207.80836388155029, 144.55751863284752, 127.59193818211159),
    obj_rtol = 1e-5,
    pg_rtol = 1e-5,
    traj_rtol = 1e-5,
    dual_rtol = 1e-4,
    angle_rel_coi_deg = Dict(
        0.01 => (0.58635778386808002, -2.2746188302938424, 0.23125000107612947),
        0.31 => (-20.062891983464247, 48.097663781225805, 55.302896441611153),
        1.0 => (6.4147083477825593, -15.380234666647793, -17.677808463467635),
    ),
    pe_mw = Dict(
        0.01 => (93.791218814672334, 7.6690296117392335e-07, 39.272662667783436),
        0.31 => (13.409208383210075, 6.2910931961370911e-07, 100.72669445026048),
        1.0 => (274.34559348070013, 104.5893169091791, 59.029324707659406),
    ),
    dual_pbalance_t001 = nothing,
    dual_delta_coi_lower_t001 = (-1.4273821831938815e-09, -1.4691704970296701e-09, -1.4324395044275904e-09),
)
