# Auto-generated by scripts/extract_simulation_pins.jl
# Source: _TSCOPF_simulations/RESULTS/bound_compare_constraint
const ACOPF_DISPATCH_CONSTRAINT_SUITE = "acopf_dispatch_constraint"

const ACOPF_DISPATCH_CONSTRAINT_PINS = (
    obj_eur = 10133.713973827314,
    pg_mw = (143.08370741301405, 198.2499993912472, 138.90835574658198),
    obj_rtol = 1e-5,
    pg_rtol = 1e-5,
    traj_rtol = 1e-5,
    dual_rtol = 1e-4,
    angle_rel_coi_deg = nothing,
    pe_mw = nothing,
    dual_pbalance_t001 = nothing,
    dual_delta_coi_lower_t001 = nothing,
)
