# Auto-generated by scripts/extract_simulation_pins.jl
# Source: _TSCOPF_simulations/RESULTS/bound_compare_gl_gen3_kron_constraint
const BOUND_COMPARE_GL_GEN3_KRON_SUITE = "bound_compare_gl_gen3_kron"

const BOUND_COMPARE_GL_GEN3_KRON_PINS = (
    obj_eur = 10133.713973829072,
    pg_mw = (143.08370746539043, 198.24999932142154, 138.90835576166057),
    obj_rtol = 1e-5,
    pg_rtol = 1e-5,
    traj_rtol = 1e-5,
    dual_rtol = 1e-4,
    angle_rel_coi_deg = Dict(
        0.01 => (-2.8484144737859833, 10.521330962546978),
        0.31 => (-0.066977913201095488, 0.24739966688654666),
        1.0 => (-0.75202930249071054, 2.7778082360750065),
    ),
    pe_mw = Dict(
        0.01 => (218.12000460861179, 253.13050415781802),
        0.31 => (272.06540968115553, 204.32337456788491),
        1.0 => (259.12371441924154, 216.90804678747816),
    ),
    dual_pbalance_t001 = nothing,
    dual_delta_coi_lower_t001 = nothing,
)
