# Auto-generated by scripts/extract_simulation_pins.jl
# Source: _TSCOPF_simulations/RESULTS/bound_compare_gl_gen3_4th_fullbus_constraint
const BOUND_COMPARE_GL_GEN3_4TH_FULLBUS_SUITE = "bound_compare_gl_gen3_4th_fullbus"

const BOUND_COMPARE_GL_GEN3_4TH_FULLBUS_PINS = (
    obj_eur = 10133.713974522941,
    pg_mw = (143.08370859734421, 198.24999938649103, 138.90835453796706),
    obj_rtol = 1e-5,
    pg_rtol = 1e-5,
    traj_rtol = 1e-5,
    dual_rtol = 1e-4,
    angle_rel_coi_deg = Dict(
        0.01 => (-5.6810483651835941, 20.984372398896905),
        0.31 => (-3.0900682886452699, 11.41393974118346),
        1.0 => (-3.8696566524281253, 14.293544259906374),
    ),
    pe_mw = Dict(
        0.01 => (204.86281045848222, 246.61360736245973),
        0.31 => (249.48721708467713, 204.41101649529384),
        1.0 => (223.17932872051199, 215.60696216275232),
    ),
    dual_pbalance_t001 = nothing,
    dual_delta_coi_lower_t001 = nothing,
)
