# Auto-generated by scripts/extract_simulation_pins.jl
# Source: _TSCOPF_simulations/RESULTS/bound_compare_dcopf_constraint
const DCOPF_DISPATCH_CONSTRAINT_SUITE = "dcopf_dispatch_constraint"

const DCOPF_DISPATCH_CONSTRAINT_PINS = (
    obj_eur = 559.21006944444434,
    pg_mw = (10, 233.5503472222222, 228.94965277777769),
    obj_rtol = 1e-5,
    pg_rtol = 1e-5,
    traj_rtol = 1e-5,
    dual_rtol = 1e-4,
    angle_rel_coi_deg = nothing,
    pe_mw = nothing,
    dual_pbalance_t001 = nothing,
    dual_delta_coi_lower_t001 = nothing,
)
