#=
 Extract scalar regression pins from a _TSCOPF_simulations bound_compare_*_constraint folder.

 Usage:
   julia --project=. scripts/extract_simulation_pins.jl <path_to_constraint_folder> [suite_name]

 Writes test/simulation_pins/pins_<suite_name>.jl (or prints to stdout if --stdout).
=#

using CSV
using DataFrames
using Printf

const SAMPLE_TIMES = (0.01, 0.31, 1.0)
const PRIMAL_RTOL = 1e-5
const DUAL_RTOL = 1e-4

function _read_table(root::String, rel::String)
    path = joinpath(root, replace(rel, '/' => '\\'))
    isfile(path) || return nothing
    return CSV.read(path, DataFrame; delim = ';')
end

function _has_time_column(df::DataFrame)
    return !isempty(names(df)) && names(df)[1] == "t"
end

function _row_at_time(df::DataFrame, t::Float64; t_start::Float64 = 0.01, t_step::Float64 = 0.01)
    if _has_time_column(df)
        col_t = df[!, 1]
        idx = findfirst(x -> isapprox(Float64(x), t; atol = 1e-9), col_t)
        idx === nothing && return nothing
        return collect(df[idx, 2:end])
    end
    # Dual CSVs without a time column: row 1 ↔ t_start.
    idx = round(Int, (t - t_start) / t_step) + 1
    (idx < 1 || idx > nrow(df)) && return nothing
    return collect(df[idx, :])
end

function _extract_trajectory(root::String, rel::String, times::Tuple{Vararg{Float64}})
    df = _read_table(root, rel)
    df === nothing && return nothing
    out = Dict{Float64, Vector{Float64}}()
    for t in times
        row = _row_at_time(df, t)
        row === nothing && continue
        out[t] = row
    end
    return isempty(out) ? nothing : out
end

function _suite_name_from_path(path::String)
    base = basename(abspath(path))
    endswith(base, "_constraint") && return String(base[1:(end - length("_constraint"))])
    return base
end

function extract_pins(root::String)
    root = abspath(root)
    isdir(root) || error("Not a directory: $root")

    opt = _read_table(root, "Dispatch/CSV/optimization_report.csv")
    opt === nothing && error("Missing Dispatch/CSV/optimization_report.csv under $root")
    obj_eur = Float64(opt[1, 2])

    gen = _read_table(root, "Dispatch/CSV/generators_report.csv")
    gen === nothing && error("Missing generators_report.csv")
    pg_mw = [Float64(gen.P_MW[i]) for i in 1:nrow(gen)]

    angle_rel = _extract_trajectory(root, "Transient_Stability/CSV/angle_rel_COI.csv", SAMPLE_TIMES)
    pe_mw = _extract_trajectory(root, "Transient_Stability/CSV/electrical_power.csv", SAMPLE_TIMES)

    dual_pbal = _extract_trajectory(root, "Transient_Stability/CSV_duals/dual_Pbalance.csv", (0.01,))
    dual_coi_lo = _extract_trajectory(root, "Transient_Stability/CSV_duals/dual_delta_COI_lower.csv", (0.01,))

    dual_pbalance_t001 = dual_pbal === nothing ? nothing : get(dual_pbal, 0.01, nothing)
    dual_delta_coi_lower_t001 = dual_coi_lo === nothing ? nothing : get(dual_coi_lo, 0.01, nothing)

    return (
        root = root,
        obj_eur = obj_eur,
        pg_mw = pg_mw,
        angle_rel_coi_deg = angle_rel,
        pe_mw = pe_mw,
        dual_pbalance_t001 = dual_pbalance_t001,
        dual_delta_coi_lower_t001 = dual_delta_coi_lower_t001,
    )
end

function _fmt_tuple(v::Vector{Float64})
    parts = [@sprintf("%.17g", x) for x in v]
    return "(" * join(parts, ", ") * ")"
end

function _fmt_time_dict(d::Union{Nothing, Dict{Float64, Vector{Float64}}})
    d === nothing && return "nothing"
    lines = String[]
    for t in sort(collect(keys(d)))
        push!(lines, "        $t => $( _fmt_tuple(d[t]) ),")
    end
    return "Dict(\n" * join(lines, "\n") * "\n    )"
end

function emit_julia_pins(suite_name::String, pins)
    io = IOBuffer()
    println(io, "# Auto-generated by scripts/extract_simulation_pins.jl")
    # Record the suite folder only. The absolute root is machine-specific and
    # would bake a local path into a tracked, published file.
    println(io, "# Source: _TSCOPF_simulations/RESULTS/$(basename(pins.root))")
    println(io, "const $(uppercase(replace(suite_name, '-' => '_')))_SUITE = $(repr(suite_name))")
    println(io, "")
    println(io, "const $(uppercase(replace(suite_name, '-' => '_')))_PINS = (")
    @printf io "    obj_eur = %.17g,\n" pins.obj_eur
    println(io, "    pg_mw = $( _fmt_tuple(pins.pg_mw) ),")
    println(io, "    obj_rtol = 1e-5,")
    println(io, "    pg_rtol = 1e-5,")
    println(io, "    traj_rtol = 1e-5,")
    println(io, "    dual_rtol = 1e-4,")
    println(io, "    angle_rel_coi_deg = $(_fmt_time_dict(pins.angle_rel_coi_deg)),")
    println(io, "    pe_mw = $(_fmt_time_dict(pins.pe_mw)),")
    if pins.dual_pbalance_t001 !== nothing
        println(io, "    dual_pbalance_t001 = $( _fmt_tuple(pins.dual_pbalance_t001) ),")
    else
        println(io, "    dual_pbalance_t001 = nothing,")
    end
    if pins.dual_delta_coi_lower_t001 !== nothing
        println(io, "    dual_delta_coi_lower_t001 = $( _fmt_tuple(pins.dual_delta_coi_lower_t001) ),")
    else
        println(io, "    dual_delta_coi_lower_t001 = nothing,")
    end
    println(io, ")")
    return String(take!(io))
end

function main()
    if length(ARGS) < 1
        println("Usage: julia --project=. scripts/extract_simulation_pins.jl <constraint_folder> [suite_name] [--stdout]")
        exit(1)
    end
    root = ARGS[1]
    stdout_only = "--stdout" in ARGS
    extra = [a for a in ARGS[2:end] if a != "--stdout"]
    suite_name = String(isempty(extra) ? _suite_name_from_path(root) : extra[1])

    pins = extract_pins(root)
    text = emit_julia_pins(suite_name, pins)

    if stdout_only
        println(text)
        return
    end

    out_dir = joinpath(@__DIR__, "..", "test", "simulation_pins")
    mkpath(out_dir)
    out_path = joinpath(out_dir, "pins_$(replace(suite_name, "bound_compare_" => "")).jl")
    write(out_path, text)
    @info "Wrote pins" out_path obj_eur=pins.obj_eur
end

main()
